### PR TITLE
30 import csv

### LINKED ISSUE #30: Import contacts from CSV
time = 2hr

### PR DESCRIPTION
**Pull request by cprghunter**

### CODE REVIEW

**Comment by cprghunter** [comment]
corresponding backedn pr: https://github.com/CSC-307-My-Contacts/my-contacts-backend/pull/9

**Review by AlexMaclean — APPROVED** [review]
The token change looks good, it was an oversight of mine not to do it myself when creating the stub for this feature. Kinda looks like you make the change in twice in 2 different commits so consider squashing when you merge so the history of the project doesn't get confusing.

The other changes I made to resolve a bug laid bare when contacts are imported without emails or phone numbers. @baileywickham @ysunkara, let me know what you think

**Review by baileywickham — APPROVED** [review]
Looks good to me. Make sure the API spec is met.

**Review by ysunkara — APPROVED** [review]
Looks good to me

**Pull request merged**
